import Head from 'next/head'
import Navbar from './components/Navbar/Navbar'
import Main from './components/Main'
import About from './components/About'
import Projects from './components/Projects'
import Contact from './components/Contacts'

export default function Home() {
  return (
    <>
      <Head>
        <title>Naufal | Mobile % Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Projects />
      <Contact />
    </>
  )
}
